### ISSUE TITLE
SDL binding lacks the button mask constants

### ISSUE THREAD

**Issue by TJYSunset** [dotnet/Silk.NET#1165]
# Summary
[`SDL_BUTTON_LMASK`, `SDL_BUTTON_MMASK`, `SDL_BUTTON_RMASK`, `SDL_BUTTON_X1MASK` and `SDL_BUTTON_X2MASK`](https://github.com/libsdl-org/SDL/blob/0a48abc860b436387c94e90c13fd0db25772e356/include/SDL3/SDL_mouse.h#L453-L457) are not present in the Silk.NET.SDL package (while the related constants `SDL_BUTTON_LEFT` and such are contained in the [`Sdl`](https://www.fuget.org/packages/Silk.NET.SDL/2.16.0/lib/netstandard2.1/Silk.NET.SDL.dll/Silk.NET.SDL/Sdl) class.)

**Comment by Beyley** [comment]
The SDL bindings are quite incomplete yes, this will be fixed in 3.0 by removing SDL support, but in the meantime: the reason they didnt get generated is likely (this is complete conjecture) due to it calling into a macro to get those, and clangsharp just isnt handling that and isnt giving us the final value

**Comment by Beyley** [comment]
You should be able to just calculate it by hand no problem, and add the constants in your code

**Comment by Perksey** [comment]
This is expected as this is how they are defined in SDL (i.e. as macros rather than enums). We only generate enums where SDL has actually defined an enum, so them appearing in `Sdl` as `const`s is to be expected.
