### ISSUE TITLE
When will the version be updated?

### ISSUE THREAD

**Issue by qian-o** [dotnet/Silk.NET#1199]
I'm doing WPF related development and need OpenGL for rendering.
At present, the project uses OpenTk to associate D3d9 with OpenGL.
I have replaced SharpDx with Silk.NET. Next, I want to replace OpenTk.
Last week, I saw Dylan Perks submit relevant code, but I don't know when Nuget will be updated.

I have been paying attention to the development of Silk.NET, and I hope it can be better and better.

**Comment by Perksey** [comment]
I have stopped working on WPF support (simply because I just don’t want to) so this will not be present in the next version of Silk.NET. I’m happy to continue working on it if someone paid for it, but it turned out to be less fun than I wanted it to be.

This is an open source project with no fixed update schedule. We did used to have a monthly update schedule, but this eventually became unneeded and unsustainable given the maintenance effort at the time. It is possible that these restart when the next update releases, but again this is open source so there’s no timeline for that.

Please don’t open issues asking when the next update is, please only open an issue if you have a genuine issue to report (like a bug or feature request). For everything else please use GitHub Discussions or Discord.

Hope this helps.

**Comment by qian-o** [comment]
Thank you for your reply.
