### ISSUE TITLE
Managed Chain overloads

### ISSUE THREAD

**Issue by Khitiara** [dotnet/Silk.NET#1611]
# Summary of feature
Vulkan methods taking a struct chain or a pointer to one should have overloads accepting the `IChain<TStart>` interfaces added previously with the previous implementation of [Chain Polymorphism](https://github.com/dotnet/Silk.NET/issues/1091)

# Comments
Yes I know this is hellish.

**Comment by Perksey** [comment]
Umm, no, this isn’t how structure chains are designed to work. Structure chains are designed to augment the API, not incur modifications to it. The only reason structure chaining exists is to make creating a singly-linked list easier. Chain polymorphism being exposed in the bindings API surface does not add anything to the bindings whatsoever, given that it is implied that you can get a head pointer from an IChain implementation.

Now I do see what you’re trying to do, you’re trying to make a way to pass in an IChain implicitly as a head pointer which you can’t do today due to the implicit operators only being on the concrete implementations. However, this can be solved with C# 11 and .NET 7. Simply define a new type like IChainOperators<THead> that contains static abstract operators, and mandate that IChain implements this. The interface needs to be separate as static abstract in interfaces attract a lot of caveats (they’re basically only intended to be used in interfaces that more resemble traits than ALI contracts). After that, consumers will be able to implicit convert IChain<T> to T*. Obviously this will be .NET 7+ only. Alternatively (or additionally) you could main Chain<T, U, V>’s base class Chain<T, U> (and so on) instead of just Chain and this achieves a similar effect. Maybe there’s a reason we haven’t done this already.

I’m not 100% sure if any of that works, but you get the idea. Improvements to the agility of chains should be done on the chains themselves rather than requiring modifications to the bindings, because if this is the case then it’s a sign that it’s just not worth it to accommodate super niche usage of the library. Chains fundamentally are an abstraction atop the surface exposed by the bindings, and are separate from the bindings themselves. Happy to hear your thoughts & will accept PRs to this end, but otherwise this issue should be closed given that it will not be implemented as described.

**Comment by Khitiara** [comment]
Your points make sense, closing
