### ISSUE TITLE
can't run WebGPU example

### ISSUE THREAD

**Issue by mikeny07** [dotnet/Silk.NET#1653]
# Summary

I attempted to test WebGPU apps by cloning the Silk.NET repository. I successfully ran most examples in the src/Lab/Experiments/ folder, including Triangle, D3D12Triangle, VeldridTriangle, etc. However, I encountered the same error for all WebGPU examples (WebGPUTest, WebGPUTexturedQuad, and WebGPUTriangle), as shown below:

"Could not load from any of the possible library names! Please ensure that the library is installed and located in the correct directory."

How can I resolve this issue?

# Comments
Tools used: Visual Studio 2022 .NET 6 on Windows 11.

**Comment by Perksey** [comment]
This is already fixed and waiting to be released in 2.18. Here is the provisional change log:

- Added SPIRV-Cross bindings
- Added Shaderc bindings
- Added SPIRV-Reflect bindings
- Added reference properties on Vulkan structure chains for its constituents
- Added extension methods to IGamepad returning Thumbsticks
- Added MoltenVK as a searchable Vulkan library name on macOS (this fixes an unintentional breaking change in 2.17)
- Updated to SDL 2.28
- Updated to DirectStorage 1.2.1
- Updated to Vulkan 1.3.256
- Updated to latest WebGPU headers
- Updated to latest OpenGL specifications
- Updated to latest OpenCL specifications
- Fixed WGPU search path on Windows (it is now "wgpu_native.dll")
- Fixed libdl.so being used instead of libdl.so.2 on versions below .NET Core 3
- Fixed VTable indices being incorrect in some DirectWrite, DirectComposition, and Direct2D functions
- Fixed GetApi not being implemented for WGL

Please note that the WGPU search path modification may be breaking in some scenarios. In addition, the libdl library name change may also be breaking, but we recommend updating to a newer version of .NET to resolve this.

To try it out early you can use the experimental feed.

**Comment by mikeny07** [comment]
Thank you for your prompt response. When using the Silk.NET NuGet package version 2.17.1 to run the same WebGPU examples (utilizing the downloaded source code), I encountered the identical error, with the error message pointing to the following line

`wgpu = WebGPU.GetApi();`

**Comment by Perksey** [comment]
Yes it’s only fixed on the experimental feed at the moment. You’ll have to wait for 2.18 to come out or use the experimental feed: https://dotnet.github.io/Silk.NET/docs/silk.net/experimental-feed.html

**Comment by vpenades** [comment]
I'm having this exact same issue trying to run WebGPUTriangle.

In my case, I replaced the project refereces with nuget packages:

```csproj


```

**Comment by Perksey** [comment]
Yes, Silk.NET.WebGPU.Native.WGPU is probably what you need.
