### ISSUE TITLE
Make WindowOptions a class

### ISSUE THREAD

**Issue by tvardero** [dotnet/Silk.NET#2019]
Please make WindowOptions as class, not as struct.

1. They are heavy to copy by value
2. They can not be used with `IOptions<>` (see [this ](https://learn.microsoft.com/en-us/dotnet/core/extensions/options)for more information), as latter has reference type generic constraint. I end up in wrapping WindowOptions in a new class with delegations for every property.

---

 ###### I use dependency injection to inject window options via constructor-injection. `IOptions` works very nice with `Microsoft.Extensions.Configuration`, and latter is used to read application configuration from different sources (json files, txt files, network, etc). Injection of `IConfiguration` to read `WindowOptions` directly is possible, but is not desirable.

**Comment by Perksey** [comment]
I don't think we're going to change this unfortunately. Some of the reasons:
1. It's a breaking change. We could do this in 3.0, but we have already removed the concept of WindowOptions and even if we hadn't we probably wouldn't want to because of reason 2.
2. The question shouldn't be "how can we change silk to make it fit DI [or insert other external component here]" it should be "what additional functionality can we add to more happily marry the two components". Taking the first approach has gains in some use cases but sacrifices in others.
