### ISSUE TITLE
Android Bluetooth permission question

### ISSUE THREAD

**Issue by Basewq** [dotnet/Silk.NET#2210]
I am assuming pull #1372 is in version 2.20.0 and 2.21.0 (the two latest versions of Silk) and contained the SDL changes which defaults to not enabling checking the bluetooth permission.
According to SDL the bluetooth permission check is ignored by default on Android (the hint SDL_HINT_JOYSTICK_HIDAPI_STEAM)
https://github.com/libsdl-org/SDL/commit/66058bbbd5083acfb0ff88c49faac76d725a711f

However, when I run the android app (just the Silk Android sample project in the repo) I am noticing the debug log shows
> [hidapi] Initializing Bluetooth

which seems to imply the hint is being set in Silk?
Is there a way to forcibly unset this hint value?

**Comment by Perksey** [comment]
That PR has been in Silk.NET since 2.17. However, I notice that we haven't rebuilt the Android binary for some time, so it's actually closer to being exactly the same for 3 years.

Silk.NET uses `SdlProvider` to create its instance. You can hijack this process using the following:
```cs
var sdl = Sdl.GetApi();
sdl.InitHint(...);
sdl = SdlProvider.SDL.Value;
```
Though I agree this shouldn't really be necessary.

Really we need to update our Android binaries.

**Comment by Basewq** [comment]
Thanks for the info.
The code doesn't work (the InitHint method is for Glfw, not the android code).
`Sdl.GetApi()` does have a SetHint, but unfortunately there's no effect, but it might not be possible to set anyway since the creation and init seems to be within `SDLActivity.onCreate`.

If you haven't rebuilt the Android binary, then that would make sense that it's not actually running the new checks (since the changed logic check is within `SDLActivity.java`).

Would be nice to have a new binary with this change, if not, then please close this as unplanned.
