### ISSUE TITLE
Silk.Net 2.21 window is stuck after minimizing

### ISSUE THREAD

**Issue by Arugin** [dotnet/Silk.NET#2240]
# Summary
Window is stuck right after minimizing. Everything works as expected in 2.20

# Steps to reproduce
- Platform: Windows
- Framework Version: .NET 7
- API: Vulkan

1. Get the sample https://github.com/dotnet/Silk.NET/tree/main/src/Lab/Experiments/ImGuiVulkan
2. Update to SIlk.Net 2.21
3. Run the sample
4. Minimize the window
5. Now it stuck and won't expand back

# Comments
If you set the version of Silk.Net and all other libraries to 2.20 everything works as expected.

Probably releated to recent changes of resize?

**Comment by qian-o** [comment]
I have encountered this problem before, where I got stuck in an infinite loop while refactoring the swap chain. This may be related to thread scheduling.

**Comment by Arugin** [comment]
I am not sure about thread scheduling, this issue is reproduced on a simple vulkan imgui sample which is single threaded.

**Comment by Perksey** [comment]
Is there a minimal repro for this?

**Comment by Arugin** [comment]
Yes, as I mentioned in the issue description, it reproduces on Imgui Vulkan sample from this repo: https://github.com/dotnet/Silk.NET/tree/main/src/Lab/Experiments/ImGuiVulkan

**Comment by Arugin** [comment]
@Perksey hey, did you reproduce this issue? I can prepare reproducable project, if this will help.

**Comment by Perksey** [comment]
My Windows PC isn't built atm, I can give it a go soon.

**Comment by Perksey** [comment]
Reproduced, will investigate now.

**Comment by Perksey** [comment]
I've identified this to be specific to the way our application is written (namely, calling `DoEvents` within an event callback).

Will investigate why we originally added this safeguard.

**Comment by Perksey** [comment]
Ok looking at this, this logic was added for the `Refresh` callback (specifically, it calls the game loop which will call DoEvents which will call the game loop on refresh etc etc)

I'm not quite sure how I want to tackle this. I do want to make it so we can't infinitely recurse, but at the same time it's causing issues and really is just a safeguard. I think I'll just reduce this to just the refresh callback specifically (as that's the most likely cause of recursion, anything else and the user should deal with the consequences of their actions, if any).

Personally I'd love to make this sort of recursion an exception, but this issue is evidence that we have actual code out in the wild using this pattern and therefore that would be irresponsible.

References:
- https://github.com/dotnet/Silk.NET/pull/1979#discussion_r1529554595
- https://discord.com/channels/521092042781229087/587346162802229298/1219682023698989067

**Comment by Arugin** [comment]
Sounds great, thanks!
