### ISSUE TITLE
Improve OpenGL examples 

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/Silk.NET#2280]
# Summary of feature

# Comments

# Does this have a proposal?
Check the documentation/proposals folder. If it doesn't have one, you may need to create one if you're making **massive breaking changes**.

**Comment by Perksey** [comment]
You haven’t filled out the issue description saying what needs to be improved. We have nothing to action on this issue.

**Comment by Shadowblitz16** [comment]
> You haven’t filled out the issue description saying what needs to be improved. We have nothing to action on this issue.

Sorry I accedently clicked post before I was ready.

**Comment by Perksey** [comment]
Ah gotcha, thanks. For the issue then, I don't think we necessarily need these. We're not intending to teach OpenGL, rather to show you how our bindings can be used. A lot of your suggestions are either unnecessary or are prescriptive of a specific game engine architecture, and we don't want to throw game engine architecture concepts into the mix of an already hard thing to teach.

**Comment by Shadowblitz16** [comment]
> Ah gotcha, thanks. For the issue then, I don't think we necessarily need these. We're not intending to teach OpenGL, rather to show you how our bindings can be used. A lot of your suggestions are either unnecessary or are prescriptive of a specific game engine architecture, and we don't want to throw game engine architecture concepts into the mix of an already hard thing to teach.

But there are not examples or tutorials for C# they are all for other languages and they are still really hard to find.

**Comment by Perksey** [comment]
I do completely understand where you are coming from. However it is just not in scope for maintainers to teach every game engine concept. I agree it’d be great to promote the usage of C# for this, and being a trailblazer in learning materials would indeed help. This is why I think I’d be on board with the community contributing Demos (instead of Tutorials) to demonstrate this functionality. This should help in providing extended resources beyond our tutorials, without overburdening the team in maintaining essentially a course in how to build a game engine. And naturally by being community contributed this further reduces the load of the maintainers team.

This is just my opinion though. I’m not a maintainer anymore, more just a shadow BDFL that tries to align the maintainers to keep the project going. They have the ultimate say in what happens. More specifically, developer experience (which includes tutorials) is @ThomasMiz’s expertise who may have comments here. But I feel like what I’ve expressed is likely to match the view of the maintainers team.

**Comment by aquagoose** [comment]
Would you perhaps be interested in something like [this](https://github.com/aquagoose/Silk.NET-Demos/tree/master/SilkDemos.Rendering3D) being added as a demo? Made this a while ago, it's just kinda sitting around so if it can be put to better use then I'm all for it.

**Comment by Shadowblitz16** [comment]
Shadows would be cool yes.
