### ISSUE TITLE
VSCode First class support

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/Silk.NET#560]
Should we look at supporting VS Code building as a first-class citizen, rather than requiring VS Studio?  This may encourage more Linux/macOS devs to contribute and improve cross-platform support.

_Originally posted by @thargy in https://github.com/dotnet/Silk.NET/pull/539#discussion_r683595818_

**Comment by tilkinsc** [comment]
I use vscode primarily and I haven't been able to build in vscode, which makes my contributions quite limited to self tested example code and tidbits.

**Comment by Perksey** [comment]
It's unclear what is required here. #322 added support in the repo for launching tutorials using VS Code, and that's more that can be said for any other IDE we support thus I feel like it is already indeed a first class citizen.

**Comment by Perksey** [comment]
I think I'm going to close this primarily because we're fully buildable on non-Windows, non-VS platforms these days (to the extent that CI builds on Apple Silicon Macs now), so any IDE that is not capable of enacting behaviour enacted by the dotnet CLI tooling should be reported to the vendors of such IDEs. Also see the previous comment.
