### ISSUE TITLE
Scalar.As to be generated by T4?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/Silk.NET#639]
Writing scalar as manually is quadratic complexity of free time 😆 

@HurricanKai if I understand correctly, it's your area. What do you think?
Also wonder if we can generate other Scalar's methods with it

**Comment by HurricanKai** [comment]
Yeah, this is true. We could likely do this with T4, tough I just don't know much about T4.
I'd prefer using some helper program for other methods because they have specific Performance tuning changes made to them.
Scalar.As was originally written by @Perksey and I pretty much never touched it since.
If you want to change it to T4 or pretty much anything else I'm happy to merge that as well, it's uncommon to be touched so feel free to do whatever you like.

**Comment by WhiteBlackGoose** [comment]
I definitely can do T4 (I use them in my prjs). The question is, how to make those cross-platform. There are some extensions, but I guess we need to make sure that those are available to any potential contributor?

**Comment by HurricanKai** [comment]
Eeeeh, I think for Scalar.As it'd be fine regardless. As I said, it's pretty much never touched.

**Comment by WhiteBlackGoose** [comment]
Gotcha. Then, assign it to me
