### ISSUE TITLE
It's time to add some docs!

### ISSUE THREAD

**Issue by makemefeelgr8** [dotnet/Silk.NET#874]
The project is 3 years old, and there is like ZERO documents. Can you believe it?!
Like, how am I supposed to get started? Do you expect me to download a triangle sample with like 1000 lines of code and 0 comments?
https://github.com/dotnet/Silk.NET/blob/main/src/Lab/Experiments/VulkanTriangle/HelloTriangleApplication.cs
Really? Like, I get it, a thin wrapper around Vulkan, most of the functions are named in the same way as the cpp alternative, I get it. But having no docs? Oh man!

Let me show you how others do it. The libraries are outdated, but the docs are there!
https://github.com/giawa/opengl4csharp
Tutorials!
https://github.com/giawa/opengl4tutorials
Github wiki!
https://github.com/luca-piccioni/OpenGL.Net/wiki

And finally, I'm going to tell you a secret. Do you know what happens to poorly documented libraries? No matter the feature set they offer, people just wouldn't use them. No documents = no library. It's that simple. What's the point of implementing new features, if nobody can use them anyway?

That's why I suggest you spend some time and actually add some docs, Getting started, FAQ and Tutorials.
Thanks in advance, guys. I was really hoping to use your stuff, but I guess I'm not doing it now cause it's not documented. It's time to look for an alternative.

**Comment by Beyley** [comment]
hi, feel free to contribute documentation! we are always open to PRs, as we know it's quite lacking, might some other examples be of good use to learn from? the vulkan one is basically worst case, the other examples are usually much smaller and easier to understand

**Comment by Perksey** [comment]
Frankly if this is how prospective users think, I’d rather have no users. Feel free to open another issue wherein you don’t make the assumption that I owe you tens of hours of my free time documenting a free library because you demanded so. Likewise, feel free to contribute your own documentation. Otherwise, deal with the fact that we make no money from this (thus we have no obligation to work on this) and we’re just going to work on whatever is most interesting to us as a result. Thanks.
